Add missing safeguards for our of range buffer reads
athombv/node-data-types pull request #34
Opened 2023-03-27 14:01 UTC by bobvandevijver

Without this change the `addCluster` call would crash when using a `single` data type in a custom cluster as the initial buffer that is being read in the zigbee-clusters library is not large enough. Safeguards on the other buffer methods prevent this for happening for the `uint` types: removing the safeguard from the `uintFromBuf` would crash the app before it has the chance to start.

2023-03-27 14:19 UTC, RobinBol requested changes

2023-03-27 14:19 UTC, RobinBol commented on lib/DataTypes.js
> +  if (buf.length - i < 4) return 0;
```suggestion
  if (buf.length - i < this.length) return 0;
```

2023-03-27 14:19 UTC, RobinBol commented on lib/DataTypes.js
> +  if (buf.length - 1 < this.length) return 0;
```suggestion
  if (buf.length - i < this.length) return 0;
```

2023-03-27 14:19 UTC, RobinBol commented on lib/DataTypes.js
> +  if (buf.length - i < 8) return 0;
```suggestion
  if (buf.length - i < this.length) return 0;
```

2023-03-27 14:31 UTC, RobinBol approved these changes

2023-03-30 07:02 UTC, hmeerlo approved these changes

2023-03-30 11:46 UTC, merged